name: getx_todo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.1.1
  equatable: 2.0.5
  json_annotation: 4.8.0
  flutter_easyloading: 3.0.5
  loading_animation_widget: 1.2.0+4
  dotted_border: 2.0.0+3
  step_progress_indicator: 1.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  build_runner: any
  json_serializable: 6.6.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

